import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Script from "next/script";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Habemus Info",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="es">
      <head>
        {/* Cambia "tu-ID-de-publicador" por el tuyo que te da Google (ej: ca-pub-123456) */}
        <Script
          async
          src="https://pagead2.googlesyndication.com/pagead/js/adsbygoogle.js?client=tu-ID-de-publicador"
          crossOrigin="anonymous"
          strategy="afterInteractive" // Carga el script después de que la página sea interactiva
        />
      </head>
      <body className="antialiased bg-gray-100 min-h-screen">{children}</body>
    </html>
  );
}

